### PR TITLE
fix: Remove client when command failed

### LINKED ISSUE #606: TCP Broken pipe on disconnect / reconnect
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
The issue is located in:  *device-modbus-go*

### Is this a regression?

Kinda.

The code at v3.1 used to open and close connection for each read request, which would give problems at high freqnency polls for certain devices. The current fix of using a client map keeps a persistent connection. Now in case the connection ever drops even temporarily, read/write requests fails until the container is restarted.

### Description and Minimal Reproduction [**REQUIRED**]

Connect any modbus device over TCP and start polling such as through autoevents. Disconnect and reconnect the device to the network.

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2025-01-15T11:51:55.458149687Z app=device-modbus source=executor.go:55 msg="AutoEvent - error occurs when reading resource DI8: error reading Regex DeviceResource(s) DI8 for DVC_1 -> write tcp 172.18.0.10:55972->XXX.XXX.XXX.XXX:502: write: broken pipe"
2025/01/15 17:21:55 modbus: sending 0b 32 00 00 00 06 03 02 00 0d 00 01
level=INFO ts=2025-01-15T11:51:55.459155047Z app=device-modbus source=driver.go:137 msg="Read command failed. Cmd:DI13 err:write tcp 172.18.0.10:55972->XXX.XXX.XXX.XXX:502: write: broken pipe \n"
level=ERROR ts=2025-01-15T11:51:55.459204454Z app=device-modbus source=executor.go:55 msg="AutoEvent - error occurs when reading resource DI13: error reading Regex DeviceResource(s) DI13 for DVC_1 -> write tcp 172.18.0.10:55972->XXX.XXX.XXX.XXX:502: write: broken pipe"
2025/01/15 17:21:55 modbus: sending 0b 33 00 00 00 06 03 02 00 0c 00 01
level=INFO ts=2025-01-15T11:51:55.459254348Z app=device-modbus source=driver.go:137 msg="Read command failed. Cmd:DI12 err:write tcp 172.18.0.10:55972->XXX.XXX.XXX.XXX:502: write: broken pipe \n"
level=ERROR ts=2025-01-15T11:51:55.459301749Z app=device-modbus source=executor.go:55 msg="AutoEvent - error occurs when reading resource DI12: error reading Regex DeviceResource(s) DI12 for DVC_1 -> write tcp 172.18.0.10:55972->XXX.XXX.XXX.XXX:502: write: broken pipe"
2025/01/15 17:21:55 modbus: sending 0b 34 00 00 00 06 03 02 00 09 00 01
level=INFO ts=2025-01-15T11:51:55.459347214Z app=device-modbus source=driver.go:137 msg="Read command failed. Cmd:DI9 err:write tcp 172.18.0.10:55972->XXX.XXX.XXX.XXX:502: write: broken pipe \n"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
Latest code at commit [2f075c7](https://github.com/edgexfoundry/device-modbus-go/commit/2f075c7931a58d709b8688ebd481c390ae67f934)

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by weichou1229**
if command failed, remove the Modbus client from the cache to allow re-establish connection next time

fixes #606

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) not impact
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) not impact
  <link to docs PR>

## Testing Instructions

- Deploy core services, device-modubs, modbus sim
- Test command, restart modbus-sim, and test command again.

### CODE REVIEW

File: internal/driver/driver.go [hunk 1]
```diff
@@ -134,7 +141,8 @@ func (d *Driver) HandleReadCommands(deviceName string, protocols map[string]mode
 	for i, req := range reqs {
 		res, err := handleReadCommandRequest(deviceClient, req)
 		if err != nil {
-			driver.Logger.Errorf("Read command failed. Cmd:%v err:%v \n", req.DeviceResourceName, err)
+			driver.Logger.Errorf("Read command failed, remove the Modbus client from the cache to allow re-establish connection next time. Cmd: %v err:%v", req.DeviceResourceName, err)
+			//d.removeDeviceClient(connectionInfo)
```
Comment (cloudxxx8) [inline internal/driver/driver.go:145]: why does it comment out?

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

File: internal/driver/driver.go (hunk 1 above)
Comment (weichou1229) [reply internal/driver/driver.go]: I forgot to uncomment is after testing. Updated.

**Review by cloudxxx8 — APPROVED** [review]
LGTM
