### PR TITLE
fix: Fix nil pointer error when sending command

### LINKED ISSUE #647: Got "runtime error" when sending GET command
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-modbus

### Is this a regression?

 Yes, the previous version in which this bug was not present was: odesa

### Description and Minimal Reproduction [**REQUIRED**]
1. Generate compose file from edgex-compose/compose-builder using: `make gen ds-modbus modbus-sim no-secty arm64`
2. Deploy service: `docker compose up -d`
3. Upload [Modbus device sample profile](https://github.com/edgexfoundry/edgex-taf/blob/main/TAF/config/device-modbus/sample_profile.yaml)
4. Create a device with the following data:
```
[
   {
      "device":{
         "origin":1471806386919,
         "name":"modbus_device",
         "description":"Test-Device",
         "adminState":"UNLOCKED",
         "operatingState":"UP",
         "protocols":{
            "modbus-tcp":{
               "Address":"modbus-sim",
               "Port":1502,
               "UnitID":1,
               "Timeout":60,
               "IdleTimeout":60
            }
         },
         "labels":[
            "device-sample"
         ],
         "location":"{lat:45.45,long:47.80}",
         "serviceName":"device-modbus",
         "profileName":"Modbus-Sample-Profile"
      },
      "apiVersion":"v3"
   }
]
```
5. Send GET command: `http://localhost:59882/api/v3/device/name/modbus_device/Modbus_DeviceValue_Boolean_RW`

## 🔥 Exception or Error
The following error is displayed in the logs of device-modbus:
<pre><code>

2025/08/11 15:21:45 http: panic serving 172.18.0.14:37610: runtime error: invalid memory address or nil pointer dereference
goroutine 104 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1947 +0xb0
panic({0xb35ff9c632a0?, 0xb35ffa8b0860?})
        runtime/panic.go:791 +0x124
net/http.(*timeoutHandler).ServeHTTP(0x40000aa2c0, {0xb35ff9eadb40, 0x40001224c0}, 0x4000416f00)
        net/http/server.go:3675 +0x654
github.com/edgexfoundry/go-mod-bootstrap/v4/bootstrap/handlers.(*HttpServer).BootstrapHandler.TimeoutWithConfig.TimeoutConfig.ToMiddleware.func9.1({0xb35ff9ec5d70, 0x40002de0a0})
        github.com/labstack/echo/v4@v4.13.4/middleware/timeout.go:126 +0x1ac
github.com/edgexfoundry/go-mod-bootstrap/v4/bootstrap/handlers.(*HttpServer).BootstrapHandler.UrlDecodeMiddleware.func5.1({0xb35ff9ec5d70, 0x40002de0a0})
        github.com/edgexfoundry/go-mod-bootstrap/v4@v4.1.0-dev.24/bootstrap/handlers/common_middleware.go:84 +0x260
github.com/edgexfoundry/go-mod-bootstrap/v4/bootstrap/handlers.(*HttpServer).BootstrapHandler.LoggingMiddleware.func4.1({0xb35ff9ec5d70, 0x40002de0a0})
        github.com/edgexfoundry/go-mod-bootstrap/v4@v4.1.0-dev.24/bootstrap/handlers/common_middleware.go:60 +0x394
github.com/edgexfoundry/go-mod-bootstrap/v4/bootstrap/handlers.ManageHeader.func1({0xb35ff9ec5d70, 0x40002de0a0})
        github.com/edgexfoundry/go-mod-bootstrap/v4@v4.1.0-dev.24/bootstrap/handlers/common_middleware.go:40 +0x204
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x400023db08, {0xb35ff9eadab0, 0x40002b01c0}, 0x4000416b40)
        github.com/labstack/echo/v4@v4.13.4/echo.go:668 +0x304
net/http.serverHandler.ServeHTTP({0x4000125620?}, {0xb35ff9eadab0?, 0x40002b01c0?}, 0x6?)
        net/http/server.go:3210 +0xbc
net/http.(*conn).serve(0x40001f47e0, {0xb35ff9eaf8d0, 0x40005c1170})
        net/http/server.go:2092 +0x4fc
created by net/http.(*Server).Serve in goroutine 39
        net/http/server.go:3360 +0x3dc
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu2204/arm64

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**
```
Docker Compose version v2.38.1
Docker Version:           27.5.1
```

### PR DESCRIPTION
**Pull request by weichou1229**
Assign the Dial func for TCPClientHandler to fix nil pointer error when sending command.

fix #647

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) not impact
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) not impact
  <link to docs PR>

## Testing Instructions

Run core services and device service to test the get and put command.

### CODE REVIEW

File: internal/driver/modbusclient.go [hunk 1]
```diff
@@ -160,6 +161,7 @@ func NewDeviceClient(connectionInfo *ConnectionInfo) (*ModbusClient, error) {
 		client.TCPClientHandler.Timeout = time.Duration(connectionInfo.Timeout) * time.Second
 		client.TCPClientHandler.IdleTimeout = time.Duration(connectionInfo.IdleTimeout) * time.Second
 		client.TCPClientHandler.Logger = log.New(os.Stdout, "", log.LstdFlags)
+		client.TCPClientHandler.Dial = (&net.Dialer{Timeout: client.TCPClientHandler.Timeout}).DialContext
```
[the remark this answers is not in the document]
Comment (weichou1229) [reply internal/driver/modbusclient.go]: Updated.

File: internal/driver/modbusclient.go [hunk 2]
```diff
@@ -155,14 +155,14 @@ func NewDeviceClient(connectionInfo *ConnectionInfo) (*ModbusClient, error) {
 	client.ModbusType = connectionInfo.Protocol
 	switch client.ModbusType {
 	case ProtocolTCP:
-		client.TCPClientHandler.Address = fmt.Sprintf("%s:%d", connectionInfo.Address, connectionInfo.Port)
+		client.TCPClientHandler = *MODBUS.NewTCPClientHandler(fmt.Sprintf("%s:%d", connectionInfo.Address, connectionInfo.Port))
```
Comment (cloudxxx8) [inline internal/driver/modbusclient.go:158]: should we change to the pointer to those handler in ModbusClient struct?

Comment (weichou1229) [reply internal/driver/modbusclient.go:158]: Currently, the get and put command works as before, I don’t think it is necessary to use the pointer. Do you have any concerns?

Comment (cloudxxx8) [reply internal/driver/modbusclient.go:158]: ok, let's keep the chage as miner as possible
