### PR TITLE
fix: handle error if primaryTable is unsupported

### LINKED ISSUE #548: Unclear error message when primaryTable is misstyped or unsupported
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

The issue is located in:  `device-modbus-go`

### Is this a regression?

Not sure

### Description and Minimal Reproduction [**REQUIRED**]

If a device profile for modbus device service has a typo (or an unsupported string) in the primaryTable attribute of any device resource, when trying to read the resource or send a command from EdgeX, the device's docker logs will output an error (shown in section below) that is not descriptive, which results hard to debug since there is no clear traceback of what is causing the error.

Steps to reproduce:
- Start an instance of EdgeX and include the modbus device service (I used edgex-compose: `make gen no-secty ds-modbus`)
- Load a profile with a resource that has the propertyTable attribute misstyped (anything that is not  one of these: "DISCRETES_INPUT", "DISCRETE_INPUTS", "COILS", "INPUT_REGISTERS", "HOLDING_REGISTERS"), for example "DISCRETE_INPUT".
- Add a device and assign that profile to it
- Follow logs: `docker logs edgex-device-modbus -f`
- Try to read that resource or send a command
- The following undescriptive error will be logged

## 🔥 Exception or Error
<pre><code>

level=INFO ts=2024-04-22T16:13:51.434038971Z app=device-modbus source=modbusclient.go:42 msg="Modbus client create RTU connection."
2024/04/22 18:13:51 http: panic serving 172.26.0.11:57294: runtime error: integer divide by zero
goroutine 286 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1868 +0xb9
panic({0xd4f260?, 0x15d52a0?})
        runtime/panic.go:920 +0x270
net/http.(*timeoutHandler).ServeHTTP(0xc000518a00, {0xfcb940, 0xc0002d4460}, 0xc0002cad00)
        net/http/server.go:3402 +0x7cf
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.(*HttpServer).BootstrapHandler.TimeoutWithConfig.TimeoutConfig.ToMiddleware.func9.1({0xfdd300, 0xc000128be0})
        github.com/labstack/echo/v4@v4.11.4/middleware/timeout.go:125 +0x1e4
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.(*HttpServer).BootstrapHandler.UrlDecodeMiddleware.func5.1({0xfdd300, 0xc000128be0})
        github.com/edgexfoundry/go-mod-bootstrap/v3@v3.2.0-dev.22/bootstrap/handlers/common_middleware.go:84 +0x2d9
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.(*HttpServer).BootstrapHandler.LoggingMiddleware.func4.1({0xfdd300, 0xc000128be0})
        github.com/edgexfoundry/go-mod-bootstrap/v3@v3.2.0-dev.22/bootstrap/handlers/common_middleware.go:60 +0x409
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.ManageHeader.func1({0xfdd300, 0xc000128be0})
        github.com/edgexfoundry/go-mod-bootstrap/v3@v3.2.0-dev.22/bootstrap/handlers/common_middleware.go:40 +0x29b
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0001a4b40, {0xfcb760?, 0xc0003969a0}, 0xc0002cac00)
        github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x399
net/http.serverHandler.ServeHTTP({0xc000035050?}, {0xfcb760?, 0xc0003969a0?}, 0x6?)
        net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0004c0900, {0xfccb08, 0xc0005124b0})
        net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 41
        net/http/server.go:3086 +0x5cb
</code></pre>

Using EdgeX UI:

image

## 🌍  Your Environment
**Deployment Environment:**

- Operating System: Ubuntu 22.04 (WSL2)
- Docker Compose version v2.24.7
- Tested with both modbus tcp and rtu with a private simulator and physical devices

**EdgeX Version [**REQUIRED**]:**
Tested in both 3.0 and 3.2(main)

**Anything else relevant?**
I propose a solution already pushed to a branch in my forked `device-modbus-go` repo, where this error is handled propperly so that the log and message references an unsupported primaryTable in the resource. Please let me know if I should create a PR

### PR DESCRIPTION
**Pull request by rcrtss**
Previously a misstyped or unsupported primaryTable in a resource led to undescriptive log and error message. This commit fixes it

Closes #548

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
_No, this only adds missing error handling of existing function._
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?)
_No, this only adds missing error handling of existing function._
  <link to docs PR>

## Testing Instructions

- Start an instance of EdgeX and include the modbus device service (I used edgex-compose: `make gen no-secty ds-modbus` and modified the modbus device service in the `docker-compose.yml` to point to the local docker image of `device-modbus-go` built from this branch)
- Load a profile with a resource that has the propertyTable attribute misstyped (anything that is not  one of these: "DISCRETES_INPUT", "DISCRETE_INPUTS", "COILS", "INPUT_REGISTERS", "HOLDING_REGISTERS"), for example `"DISCRETES_INPUTS"` (which is misstyped)
- Add a device and assign that profile to it
- Follow logs: `docker logs edgex-device-modbus -f`
- Try to read that resource or send a command
- The following error will be logged and the user message is now 500 with descriptive message:

```
level=INFO ts=2024-04-24T09:03:40.928611388Z app=device-modbus source=modbusclient.go:42 msg="Modbus client create RTU connection."
level=INFO ts=2024-04-24T09:03:40.928676796Z app=device-modbus source=driver.go:126 msg="Read command failed. Cmd:exampleResource err:primaryTable DISCRETES_INPUTS not supported \n"
level=ERROR ts=2024-04-24T09:03:40.928712381Z app=device-modbus source=restrouter.go:159 X-Correlation-ID=4cf9deb0-6d32-49c9-af0e-f248597038d1 msg="error reading Regex DeviceResource(s) exampleResource for example-device -> primaryTable DISCRETES_INPUTS not supported"
```

image

### CODE REVIEW

File: internal/driver/deviceclient.go [hunk 1]
```diff
@@ -72,7 +72,10 @@ func createCommandInfo(req *models.CommandRequest) (*CommandInfo, error) {
 			return nil, errors.NewCommonEdgeX(errors.KindLimitExceeded, fmt.Sprintf("register size should be within the range of 1~123, get %v.", length), nil)
 		}
 	} else {
-		length = calculateAddressLength(primaryTable, rawType)
+		length, err = calculateAddressLength(primaryTable, rawType)
+		if err != nil {
+			return nil, err
```
Comment (cloudxxx8) [inline internal/driver/deviceclient.go:77]:
```suggestion
			return nil, errors.NewCommonEdgeXWrapper(err)
```

this is the way to record the error calling line for the future debug

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM
thanks for the contribution

**Comment by rcrtss** [comment]
> could you please sign the commit and squash to one, or DCO and Semantic PR cannot be passed?

Done!
