### PR TITLE
Check request attribute before convert to other value type

### LINKED ISSUE #9: Fail to cast value from interface to string
Here is  a potential issue when casting value at https://github.com/edgexfoundry/device-modbus-go/blob/master/internal/driver/deviceclient.go#L67
```
INFO: 2019/01/08 02:54:03 Modbus client create RTU connection.
2019/01/08 02:54:03 http: panic serving 172.18.0.9:60124: interface conversion: interface {} is nil, not string
goroutine 162 [running]:
net/http.(*conn).serve.func1(0xc0002f2d20)
    /usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x796c00, 0xc0002ff770)
    /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/edgexfoundry/device-modbus-go/internal/driver.createCommandInfo(0xc00015d020, 0x10, 0xc000162f40, 0x13, 0x0, 0x0, 0xc00015d200, 0x5, 0xac39f2, 0x1, ...)
    /go/src/github.com/edgexfoundry/device-modbus-go/internal/driver/deviceclient.go:69 +0x385
github.com/edgexfoundry/device-modbus-go/internal/driver.(*Driver).handleReadCommandRequest
```

### PR DESCRIPTION
**Pull request by weichou1229**
Fix #9 
Add an attribute checker to make sure all requests attribute are valid and then device-modbus can parse interface safely.

### CODE REVIEW

File: internal/driver/deviceclient.go [hunk 1]
```diff
@@ -64,28 +64,28 @@ func createConnectionInfo(addr models.Addressable) (*ConnectionInfo, error) {
 }
 
 func createCommandInfo(object models.DeviceObject) *CommandInfo {
-	var primaryTable, _ = object.Attributes["primaryTable"].(string)
-
-	var startingAddress, _ = strconv.Atoi(object.Attributes["startingAddress"].(string))
-	var startingAddressUint16 = uint16(startingAddress - 1)
+	primaryTable, _ := toString(object.Attributes["primaryTable"])
+	startingAddress, _ := toUint16(object.Attributes["startingAddress"])
```
Comment (cloudxxx8) [inline internal/driver/deviceclient.go]: why those two error variables are ignored?  They should be handled if something goes wrong

Comment (weichou1229) [reply internal/driver/deviceclient.go]: I check these attributes at https://github.com/edgexfoundry/device-modbus-go/pull/10/files#diff-54a06bb7cfa1776ea4ef16cfe03e9cedR35.
